language: python

python:
  - "2.7"
  - "3.5"

before_install:
- echo arangodb3 arangodb/password password root | sudo debconf-set-selections  # set username 'root'
- echo arangodb3 arangodb/password_again password root | sudo debconf-set-selections  # set password 'root'
- chmod +x setup_arangodb.sh
- ./setup_arangodb.sh

install: pip install -r tests/python_requirements.txt

script: python -m unittest discover tests/
